<?php

namespace frontend\modules\admin;

use yii\helpers\Url;
use Yii;
/**
 * admin module definition class
 */
class Module extends \yii\base\Module
{
    /**
     * {@inheritdoc}
     */
    public $controllerNamespace = 'frontend\modules\admin\controllers';
    public $layout = '//admin';

    /**
     * {@inheritdoc}
     */

    public function beforeAction($action)
    {
        if(!Yii::$app->user->isGuest) {
            if (Yii::$app->user->identity->role == 1){
                return parent::beforeAction($action); // TODO: Change the autogenerated stub
            }
            return Yii::$app->response->redirect(Url::to(['/login']));
        }
        return Yii::$app->response->redirect(Url::to(['/login']));
    }

    public function init()
    {
        parent::init();
        \Yii::$app->errorHandler->errorAction = 'admin/default/error';

        // custom initialization code goes here
    }
}
